name: Build Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: arm64
            rust_target: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: amd64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            arch: arm64
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            arch: amd64
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.rust_target }}

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: |
          cd libgroth16
          cross build --release --target ${{ matrix.rust_target }}

      - name: Prepare OS_NAME and VERSION
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "OS_NAME=linux" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "OS_NAME=osx" >> $GITHUB_ENV
          fi
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
        if: matrix.os != 'windows-latest'

      - name: Prepare OS_NAME and VERSION fow windows
        run: |
          echo "OS_NAME=win" >> $env:GITHUB_ENV
          echo "VERSION=$($env:GITHUB_REF -replace '.*/', '')" >> $env:GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
        if: matrix.os == 'windows-latest'
        shell: pwsh

      - name: Create directories
        run: mkdir -p libgroth16/target/${{ matrix.rust_target }}/release
        if: matrix.os != 'windows-latest'

      - name: Create directories for windows
        run: New-Item -Path libgroth16/target/${{ matrix.rust_target }}/release -ItemType Directory -Force
        if: matrix.os == 'windows-latest'
        shell: pwsh

      - name: Zip artifact
        run: |
          cd libgroth16/target/${{ matrix.rust_target }}/release
          zip -r libgroth16-${{ env.OS_NAME }}-${{ matrix.arch }}-${{ env.VERSION }}.zip libgroth16.*
        if: matrix.os != 'windows-latest'

      - name: Zip artifact on Windows
        run: |
          cd libgroth16/target/${{ matrix.rust_target }}/release
          Compress-Archive -Path libgroth16.* -DestinationPath libgroth16-${{ env.OS_NAME }}-${{ matrix.arch }}-${{ env.VERSION }}.zip
        if: matrix.os == 'windows-latest'
        shell: pwsh

      - name: List directory contents on Windows
        run: Get-ChildItem -Path libgroth16/target/${{ matrix.rust_target }}/release -Force
        if: matrix.os == 'windows-latest'
        shell: pwsh

      - name: Upload zips to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libgroth16/target/${{ matrix.rust_target }}/release/libgroth16-${{ env.OS_NAME }}-${{ matrix.arch }}-${{ env.VERSION }}.zip
          asset_name: libgroth16-${{ env.OS_NAME }}-${{ matrix.arch }}-${{ env.VERSION }}.zip
          tag: ${{ github.ref }}